import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { TerrainGrid, TerrainType, TERRAIN_LEGEND } from '../src/simulation/world/TerrainGrid.js';
import { VegetationGrid } from '../src/simulation/world/VegetationGrid.js';
import { SimulationEngine } from '../src/simulation/engine/SimulationEngine.js';

/**
 * Trees (TREES-FLIGHT-VULTURE-PLAN.md phase T1).
 *
 * Two claims are load-bearing and the rest are properties:
 *
 *   1. **Off leaves no trace.** With both counts at 0 the generator returns
 *      before its first draw, so a world is bit-for-bit the world it was.
 *   2. **Tree cells are not forage cells.** Trees are placed last, so lakes,
 *      rock, cover and thicket land on exactly the same cells with trees on as
 *      with them off; tree cells themselves have zero grass capacity.
 *
 * Both are asserted directly rather than inferred from a population number.
 */

const WOODED = Object.freeze({ treeGroves: 6, treeSingles: 40 });
// ⚠ Explicit, not `{}`: trees are in the demo defaults now, so an empty
// params object is a *wooded* world. The control has to say so.
const TREELESS = Object.freeze({ treeGroves: 0, treeSingles: 0 });

const grid = (params, seed = 42) => new TerrainGrid({ width: 128, height: 128, seed, params });

describe('trees: terrain properties', () => {
  const wooded = grid(WOODED);
  const tree = firstCell(wooded, TerrainType.TREE);

  test('passable and barely slower — walking under a tree is walking', () => {
    assert.equal(TERRAIN_LEGEND[TerrainType.TREE].passable, true);
    assert.equal(wooded.isPassable(...tree), true);
    // ⚠ Deliberately unlike thicket (0.1): the movement system treats a *slow*
    // cell's edge as a wall, and an animal that turned away from the canopy
    // would defeat the layer.
    assert.ok(wooded.speedModifierAt(...tree) >= 0.8, `expected near-open going, got ${wooded.speedModifierAt(...tree)}`);
  });

  test('⚠ does NOT block line of sight, but does conceal a little', () => {
    assert.equal(wooded.blocksSightAt(...tree), false, 'you see straight past a scattered canopy');
    const concealment = wooded.concealmentAt(...tree);
    assert.ok(concealment > 0, 'a trunk and a canopy break an outline');
    assert.ok(concealment < 1, 'staying under 1 is what keeps the raycast boolean unchanged');
    assert.ok(concealment < wooded.concealmentAt(...firstCell(wooded, TerrainType.COVER)), 'less than a stand of brush');
  });

  test('shelters from the weather, through the world chokepoint', () => {
    const engine = new SimulationEngine({ seed: 42, config: { terrain: WOODED } });
    const cell = firstCell(engine.world.terrain, TerrainType.TREE);
    assert.equal(engine.world.isShelteredAt(cell[0] + 0.5, cell[1] + 0.5), true);
    // A tree is not a thicket, and the predicate that decides whether movement
    // refuses a step must say so.
    assert.equal(engine.world.isThicketAt(cell[0] + 0.5, cell[1] + 0.5), false);
  });
});

describe('trees: placement', () => {
  test('⚠ zero counts spend no draws — every other tree param is unread', () => {
    // The claim is that `#scatterTrees` returns *before its first draw* when
    // both counts are 0. If it did not, these two worlds would differ: they
    // disagree about every remaining tree parameter, so any draw taken (or any
    // param read) on the way to planting nothing would move the map.
    //
    // ⚠ The stronger form of this — identical to a world generated by an engine
    // that has never heard of trees — cannot be written here, because this tree
    // always has them. It was taken against a clean HEAD checkout instead:
    // seeds 1/2/42 × 1500 ticks, state + terrain + vegetation hashes matching
    // (2026-08-03).
    const a = grid({ ...TREELESS, treeGroveDensity: 0.4, treeClusterMax: 2, treeGroveMaxRadius: 5, treeGroveMaxSteps: 6 });
    const b = grid({ ...TREELESS, treeGroveDensity: 0.9, treeClusterMax: 0, treeGroveMaxRadius: 12, treeGroveMaxSteps: 20 });
    assert.equal(a.countByType()[TerrainType.TREE], 0);
    assert.deepEqual(a.toRunLength(), b.toRunLength());
  });

  test('⚠⚠ placed last: every other terrain lands exactly where it did', () => {
    const bare = grid(TREELESS);
    const wooded = grid(WOODED);
    let trees = 0;
    for (let y = 0; y < bare.height; y += 1) {
      for (let x = 0; x < bare.width; x += 1) {
        const before = bare.codeAt(x, y);
        const after = wooded.codeAt(x, y);
        if (after === TerrainType.TREE) {
          trees += 1;
          // The only cell a tree may take is one that was open ground.
          assert.equal(before, TerrainType.GROUND, `a tree buried terrain ${before} at ${x},${y}`);
        } else {
          assert.equal(after, before, `terrain shifted at ${x},${y}`);
        }
      }
    }
    assert.ok(trees > 0, 'the wooded world has trees in it');
  });

  test('⚠⚠ no two trees touch, anywhere on the map', () => {
    // The spacing rule (2026-08-08), asserted over a heavily wooded world so it
    // covers both passes and the seams where they overlap: groves, lone trees,
    // their companions, and a grove landing on top of a single.
    const dense = grid({ treeGroves: 20, treeSingles: 200, treeGroveDensity: 0.9, treeClusterMax: 2 });
    assert.equal(maxClumpSize(dense), 1, 'a clump of adjacent trees is the thicket silhouette trees exist to avoid');
  });

  test('a dense stand is trees 2–3 cells apart, not a blob', () => {
    // The positive half of the same claim: forbidding adjacency must not simply
    // scatter trees to the winds. The overwhelming majority still have close
    // company — just not touching.
    const gaps = nearestNeighbourGaps(grid({ treeGroves: 12, treeSingles: 80 }));
    assert.ok(gaps.length > 100, 'enough trees to talk about a distribution');
    const close = gaps.filter((d) => d <= 3).length;
    assert.ok(close / gaps.length >= 0.8, `only ${close}/${gaps.length} trees have a neighbour within 3 cells`);
  });

  test('spacing 1 is the off state for the rule, with the layer still on', () => {
    // ⚠ Distinct from `treeGroves: 0, treeSingles: 0`, which is the off state for
    // the *layer*. At spacing 1 a tree needs only its own cell, so the clumping
    // the rule exists to prevent comes back — which is what proves the rule is
    // doing the work and not some other change to the pass.
    const loose = grid({ treeGroves: 12, treeSingles: 80, treeSpacing: 1 });
    assert.ok(maxClumpSize(loose) > 1, 'without the rule, trees touch again');
  });

  test('groves are scattered, not solid — open ground survives inside one', () => {
    // A grove-only world: every tree came from a disc, so the canopy fraction
    // inside the wooded region is the density and never 1.
    const groves = grid({ ...TREELESS, treeGroves: 8 });
    const counts = groves.countByType();
    assert.ok(counts[TerrainType.TREE] > 0, 'groves exist');
    // The neighbourhood of a grove cell holds open ground: a filled disc would
    // be a thicket wearing a different name.
    const [tx, ty] = firstCell(groves, TerrainType.TREE);
    let open = 0;
    for (let dy = -2; dy <= 2; dy += 1) {
      for (let dx = -2; dx <= 2; dx += 1) {
        if (groves.codeAt(tx + dx, ty + dy) === TerrainType.GROUND) open += 1;
      }
    }
    assert.ok(open > 0, 'a grove is semi-open woodland, not a stand');
  });

  test('lone trees come in loose ones, twos and threes', () => {
    // ⚠ **Rewritten 2026-08-08 with the spacing rule**: the shapes are the same
    // — a lone tree, a pair, a triplet — but a companion now stands 2–3 cells
    // off rather than on an 8-neighbour, so the clump is no longer a *connected*
    // clump and cannot be counted as one. Clustering is measured against its own
    // control instead: turning it on adds trees, and every one it adds keeps its
    // distance.
    const singles = { ...TREELESS, treeSingles: 60 };
    const lone = grid({ ...singles, treeClusterMax: 0 });
    const clustered = grid({ ...singles, treeClusterMax: 2 });
    const loneCount = lone.countByType()[TerrainType.TREE];
    const clusteredCount = clustered.countByType()[TerrainType.TREE];
    assert.ok(loneCount > 0, 'scattered trees exist');
    assert.ok(clusteredCount > loneCount * 1.3, `companions barely landed: ${loneCount} → ${clusteredCount}`);
    assert.equal(maxClumpSize(clustered), 1, 'a companion is near its seed, never against it');
    // The companions really are *company*: with clustering on, a clear majority
    // of trees have another within the clump ring.
    const gaps = nearestNeighbourGaps(clustered);
    const close = gaps.filter((d) => d <= 3).length;
    assert.ok(close / gaps.length >= 0.5, `only ${close}/${gaps.length} trees have close company`);
  });

  test('a companion count cannot shift the stream — the draw budget is fixed', () => {
    // With clustering off, every single spends the same five draws it spends
    // with clustering on, so the *positions* of the seed trees are identical and
    // only the companions differ.
    //
    // ⚠ This is also what the deferred companion planting is for (2026-08-08):
    // under the spacing rule an inline companion would reject a later seed tree
    // three cells away, so `treeClusterMax` would decide where the lone trees
    // *are* and this assertion would fail on collisions rather than on a stream
    // shift. Seeds are all planted first; companions follow.
    const clustered = grid({ ...TREELESS, treeSingles: 40, treeClusterMax: 2 });
    const lone = grid({ ...TREELESS, treeSingles: 40, treeClusterMax: 0 });
    for (let y = 0; y < lone.height; y += 1) {
      for (let x = 0; x < lone.width; x += 1) {
        if (lone.codeAt(x, y) !== TerrainType.TREE) continue;
        assert.equal(clustered.codeAt(x, y), TerrainType.TREE, `seed tree at ${x},${y} moved`);
      }
    }
  });

  test('deterministic, and passable ground stays one connected region', () => {
    assert.deepEqual(grid(WOODED).toRunLength(), grid(WOODED).toRunLength());
    // Trees are passable, so they can neither strand ground nor be carved
    // through — the guarantee holds over a heavily wooded map.
    const dense = grid({ treeGroves: 20, treeSingles: 200, treeGroveDensity: 0.9, treeClusterMax: 2 });
    assert.equal(passableComponents(dense), 1);
  });
});

describe('trees: vegetation', () => {
  test('tree cells are bare and stay bare through regrowth', () => {
    const terrain = grid(WOODED);
    const vegetation = new VegetationGrid({ terrain, seed: 7, params: {} });
    let trees = 0;
    for (let y = 0; y < terrain.height; y += 1) {
      for (let x = 0; x < terrain.width; x += 1) {
        if (terrain.codeAt(x, y) !== TerrainType.TREE) continue;
        trees += 1;
        assert.equal(vegetation.capacityAt(x, y), 0, `tree cell ${x},${y} has grass capacity`);
        assert.equal(vegetation.biomassAt(x, y), 0, `tree cell ${x},${y} starts with grass`);
        assert.equal(vegetation.levelAt(x, y), 0, `tree cell ${x},${y} projects forage`);
      }
    }
    assert.ok(trees > 0, 'the wooded world has trees');
    for (let i = 0; i < 200; i += 1) vegetation.grow({ growthRate: 0.2, seedFloor: 0.1 });
    for (let y = 0; y < terrain.height; y += 1) {
      for (let x = 0; x < terrain.width; x += 1) {
        if (terrain.codeAt(x, y) !== TerrainType.TREE) continue;
        assert.equal(vegetation.biomassAt(x, y), 0, `tree cell ${x},${y} regrew grass`);
      }
    }
  });

  test('zero-capacity tree cells do not perturb non-tree seeded vegetation', () => {
    const bare = new VegetationGrid({ terrain: grid(TREELESS), seed: 7, params: {} });
    const wooded = new VegetationGrid({ terrain: grid(WOODED), seed: 7, params: {} });
    const terrain = grid(WOODED);
    for (let y = 0; y < terrain.height; y += 1) {
      for (let x = 0; x < terrain.width; x += 1) {
        if (terrain.codeAt(x, y) === TerrainType.TREE) continue;
        assert.equal(
          wooded.biomassAt(x, y),
          bare.biomassAt(x, y),
          `non-tree vegetation shifted at ${x},${y}`,
        );
      }
    }
  });

  test('restoring legacy biomass cannot put grass under a tree', () => {
    const terrain = grid(WOODED);
    const vegetation = new VegetationGrid({ terrain, seed: 7, params: {} });
    const [tx, ty] = firstCell(terrain, TerrainType.TREE);
    const saved = vegetation.serialize();
    saved.biomass[ty * terrain.width + tx] = 5;
    vegetation.restore(saved);
    assert.equal(vegetation.biomassAt(tx, ty), 0);
    assert.equal(vegetation.levelAt(tx, ty), 0);
  });
});

function firstCell(grid, code) {
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) if (grid.codeAt(x, y) === code) return [x, y];
  }
  throw new Error(`no cell of code ${code}`);
}

/** The largest 8-connected clump of tree cells — 1 when no two trees touch. */
function maxClumpSize(grid) {
  return clumpSizes(grid).reduce((max, size) => (size > max ? size : max), 0);
}

/**
 * For every tree, the Chebyshev distance to the nearest other tree, capped at
 * `MAX_GAP` (a tree with no company inside that window reports the cap). This is
 * the distribution the spacing rule is about: 1 must never appear, and most of
 * the mass should sit at 2–3.
 */
const MAX_GAP = 6;
function nearestNeighbourGaps(grid) {
  const gaps = [];
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) {
      if (grid.codeAt(x, y) !== TerrainType.TREE) continue;
      let nearest = MAX_GAP;
      for (let r = 1; r < MAX_GAP && nearest === MAX_GAP; r += 1) {
        for (let dy = -r; dy <= r && nearest === MAX_GAP; dy += 1) {
          for (let dx = -r; dx <= r; dx += 1) {
            if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue; // the ring only
            if (grid.codeAt(x + dx, y + dy) === TerrainType.TREE) {
              nearest = r;
              break;
            }
          }
        }
      }
      gaps.push(nearest);
    }
  }
  return gaps;
}

/** Sizes of the 8-connected clumps of tree cells. */
function clumpSizes(grid) {
  const seen = new Set();
  const sizes = [];
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) {
      if (grid.codeAt(x, y) !== TerrainType.TREE || seen.has(`${x},${y}`)) continue;
      let size = 0;
      const stack = [[x, y]];
      seen.add(`${x},${y}`);
      while (stack.length > 0) {
        const [cx, cy] = stack.pop();
        size += 1;
        for (let dy = -1; dy <= 1; dy += 1) {
          for (let dx = -1; dx <= 1; dx += 1) {
            const key = `${cx + dx},${cy + dy}`;
            if (seen.has(key) || grid.codeAt(cx + dx, cy + dy) !== TerrainType.TREE) continue;
            seen.add(key);
            stack.push([cx + dx, cy + dy]);
          }
        }
      }
      sizes.push(size);
    }
  }
  return sizes;
}

/** Count of 4-connected components of passable cells. */
function passableComponents(grid) {
  const seen = new Set();
  let components = 0;
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) {
      if (!grid.isPassable(x, y) || seen.has(`${x},${y}`)) continue;
      components += 1;
      const stack = [[x, y]];
      seen.add(`${x},${y}`);
      while (stack.length > 0) {
        const [cx, cy] = stack.pop();
        for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
          const key = `${cx + dx},${cy + dy}`;
          if (seen.has(key) || !grid.isPassable(cx + dx, cy + dy)) continue;
          seen.add(key);
          stack.push([cx + dx, cy + dy]);
        }
      }
    }
  }
  return components;
}
