import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { TerrainGrid, TerrainType, TERRAIN_LEGEND } from '../src/simulation/world/TerrainGrid.js';
import { VegetationGrid } from '../src/simulation/world/VegetationGrid.js';
import { SimulationEngine } from '../src/simulation/engine/SimulationEngine.js';

/**
 * Trees (TREES-FLIGHT-VULTURE-PLAN.md phase T1).
 *
 * Two claims are load-bearing and the rest are properties:
 *
 *   1. **Off leaves no trace.** With both counts at 0 the generator returns
 *      before its first draw, so a world is bit-for-bit the world it was.
 *   2. **On shifts nothing that came before it.** Trees are placed last, so
 *      lakes, rock, cover and thicket land on exactly the same cells with trees
 *      on as with them off — and (because a tree grows grass exactly as well as
 *      the ground it replaced) so does the whole vegetation field.
 *
 * Both are asserted directly rather than inferred from a population number.
 */

const WOODED = Object.freeze({ treeGroves: 6, treeSingles: 40 });
// ⚠ Explicit, not `{}`: trees are in the demo defaults now, so an empty
// params object is a *wooded* world. The control has to say so.
const TREELESS = Object.freeze({ treeGroves: 0, treeSingles: 0 });

const grid = (params, seed = 42) => new TerrainGrid({ width: 128, height: 128, seed, params });

describe('trees: terrain properties', () => {
  const wooded = grid(WOODED);
  const tree = firstCell(wooded, TerrainType.TREE);

  test('passable and barely slower — walking under a tree is walking', () => {
    assert.equal(TERRAIN_LEGEND[TerrainType.TREE].passable, true);
    assert.equal(wooded.isPassable(...tree), true);
    // ⚠ Deliberately unlike thicket (0.1): the movement system treats a *slow*
    // cell's edge as a wall, and an animal that turned away from the canopy
    // would defeat the layer.
    assert.ok(wooded.speedModifierAt(...tree) >= 0.8, `expected near-open going, got ${wooded.speedModifierAt(...tree)}`);
  });

  test('⚠ does NOT block line of sight, but does conceal a little', () => {
    assert.equal(wooded.blocksSightAt(...tree), false, 'you see straight past a scattered canopy');
    const concealment = wooded.concealmentAt(...tree);
    assert.ok(concealment > 0, 'a trunk and a canopy break an outline');
    assert.ok(concealment < 1, 'staying under 1 is what keeps the raycast boolean unchanged');
    assert.ok(concealment < wooded.concealmentAt(...firstCell(wooded, TerrainType.COVER)), 'less than a stand of brush');
  });

  test('shelters from the weather, through the world chokepoint', () => {
    const engine = new SimulationEngine({ seed: 42, config: { terrain: WOODED } });
    const cell = firstCell(engine.world.terrain, TerrainType.TREE);
    assert.equal(engine.world.isShelteredAt(cell[0] + 0.5, cell[1] + 0.5), true);
    // A tree is not a thicket, and the predicate that decides whether movement
    // refuses a step must say so.
    assert.equal(engine.world.isThicketAt(cell[0] + 0.5, cell[1] + 0.5), false);
  });
});

describe('trees: placement', () => {
  test('⚠ zero counts spend no draws — every other tree param is unread', () => {
    // The claim is that `#scatterTrees` returns *before its first draw* when
    // both counts are 0. If it did not, these two worlds would differ: they
    // disagree about every remaining tree parameter, so any draw taken (or any
    // param read) on the way to planting nothing would move the map.
    //
    // ⚠ The stronger form of this — identical to a world generated by an engine
    // that has never heard of trees — cannot be written here, because this tree
    // always has them. It was taken against a clean HEAD checkout instead:
    // seeds 1/2/42 × 1500 ticks, state + terrain + vegetation hashes matching
    // (2026-08-03).
    const a = grid({ ...TREELESS, treeGroveDensity: 0.4, treeClusterMax: 2, treeGroveMaxRadius: 5, treeGroveMaxSteps: 6 });
    const b = grid({ ...TREELESS, treeGroveDensity: 0.9, treeClusterMax: 0, treeGroveMaxRadius: 12, treeGroveMaxSteps: 20 });
    assert.equal(a.countByType()[TerrainType.TREE], 0);
    assert.deepEqual(a.toRunLength(), b.toRunLength());
  });

  test('⚠⚠ placed last: every other terrain lands exactly where it did', () => {
    const bare = grid(TREELESS);
    const wooded = grid(WOODED);
    let trees = 0;
    for (let y = 0; y < bare.height; y += 1) {
      for (let x = 0; x < bare.width; x += 1) {
        const before = bare.codeAt(x, y);
        const after = wooded.codeAt(x, y);
        if (after === TerrainType.TREE) {
          trees += 1;
          // The only cell a tree may take is one that was open ground.
          assert.equal(before, TerrainType.GROUND, `a tree buried terrain ${before} at ${x},${y}`);
        } else {
          assert.equal(after, before, `terrain shifted at ${x},${y}`);
        }
      }
    }
    assert.ok(trees > 0, 'the wooded world has trees in it');
  });

  test('groves are scattered, not solid — open ground survives inside one', () => {
    // A grove-only world: every tree came from a disc, so the canopy fraction
    // inside the wooded region is the density and never 1.
    const groves = grid({ ...TREELESS, treeGroves: 8 });
    const counts = groves.countByType();
    assert.ok(counts[TerrainType.TREE] > 0, 'groves exist');
    // The neighbourhood of a grove cell holds open ground: a filled disc would
    // be a thicket wearing a different name.
    const [tx, ty] = firstCell(groves, TerrainType.TREE);
    let open = 0;
    for (let dy = -2; dy <= 2; dy += 1) {
      for (let dx = -2; dx <= 2; dx += 1) {
        if (groves.codeAt(tx + dx, ty + dy) === TerrainType.GROUND) open += 1;
      }
    }
    assert.ok(open > 0, 'a grove is semi-open woodland, not a stand');
  });

  test('lone trees come in ones, twos and threes', () => {
    const clumps = clumpSizes(grid({ ...TREELESS, treeSingles: 60 }));
    assert.ok(clumps.length > 0, 'scattered trees exist');
    for (const size of [1, 2, 3]) {
      assert.ok(clumps.includes(size), `no clump of ${size} — all three shapes should occur`);
    }
    // ⚠ **A proportion, not a maximum**, and the difference is a real property
    // of the generator rather than a loosened assertion: nothing stops two
    // independently scattered clumps landing next to each other and reading as
    // one larger one. Measured at 60 singles on 128², ~97% of clumps are 1–3
    // and the rest are chance merges. A hard ceiling here would be asserting
    // that the scatter never collides, which is not true and should not be.
    const small = clumps.filter((size) => size <= 3).length;
    assert.ok(small / clumps.length >= 0.9, `only ${small}/${clumps.length} clumps are lone/pair/triplet`);
  });

  test('a companion count cannot shift the stream — the draw budget is fixed', () => {
    // With clustering off, every single spends the same five draws it spends
    // with clustering on, so the *positions* of the seed trees are identical and
    // only the companions differ.
    const clustered = grid({ ...TREELESS, treeSingles: 40, treeClusterMax: 2 });
    const lone = grid({ ...TREELESS, treeSingles: 40, treeClusterMax: 0 });
    for (let y = 0; y < lone.height; y += 1) {
      for (let x = 0; x < lone.width; x += 1) {
        if (lone.codeAt(x, y) !== TerrainType.TREE) continue;
        assert.equal(clustered.codeAt(x, y), TerrainType.TREE, `seed tree at ${x},${y} moved`);
      }
    }
  });

  test('deterministic, and passable ground stays one connected region', () => {
    assert.deepEqual(grid(WOODED).toRunLength(), grid(WOODED).toRunLength());
    // Trees are passable, so they can neither strand ground nor be carved
    // through — the guarantee holds over a heavily wooded map.
    const dense = grid({ treeGroves: 20, treeSingles: 200, treeGroveDensity: 0.9, treeClusterMax: 2 });
    assert.equal(passableComponents(dense), 1);
  });
});

describe('trees: vegetation', () => {
  test('⚠⚠ grass grows under a tree, and the vegetation field is unshifted', () => {
    // The load-bearing half: `#seed` draws initial biomass only where capacity
    // is positive, so a suitability that crossed zero would re-roll the whole
    // field of every wooded seed. At treeSuitability 1 the field is identical.
    const bare = new VegetationGrid({ terrain: grid(TREELESS), seed: 7, params: {} });
    const wooded = new VegetationGrid({ terrain: grid(WOODED), seed: 7, params: {} });
    assert.deepEqual(wooded.serialize(), bare.serialize());
  });

  test('a tree cell carries carrying capacity, unlike a thicket', () => {
    const terrain = grid(WOODED);
    const vegetation = new VegetationGrid({ terrain, seed: 7, params: {} });
    const [tx, ty] = firstCell(terrain, TerrainType.TREE);
    const [hx, hy] = firstCell(terrain, TerrainType.THICKET);
    assert.ok(vegetation.capacityAt(tx, ty) > 0, 'open woodland grows grass');
    assert.equal(vegetation.capacityAt(hx, hy), 0, 'a dense stand does not');
  });
});

function firstCell(grid, code) {
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) if (grid.codeAt(x, y) === code) return [x, y];
  }
  throw new Error(`no cell of code ${code}`);
}

/** Sizes of the 8-connected clumps of tree cells. */
function clumpSizes(grid) {
  const seen = new Set();
  const sizes = [];
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) {
      if (grid.codeAt(x, y) !== TerrainType.TREE || seen.has(`${x},${y}`)) continue;
      let size = 0;
      const stack = [[x, y]];
      seen.add(`${x},${y}`);
      while (stack.length > 0) {
        const [cx, cy] = stack.pop();
        size += 1;
        for (let dy = -1; dy <= 1; dy += 1) {
          for (let dx = -1; dx <= 1; dx += 1) {
            const key = `${cx + dx},${cy + dy}`;
            if (seen.has(key) || grid.codeAt(cx + dx, cy + dy) !== TerrainType.TREE) continue;
            seen.add(key);
            stack.push([cx + dx, cy + dy]);
          }
        }
      }
      sizes.push(size);
    }
  }
  return sizes;
}

/** Count of 4-connected components of passable cells. */
function passableComponents(grid) {
  const seen = new Set();
  let components = 0;
  for (let y = 0; y < grid.height; y += 1) {
    for (let x = 0; x < grid.width; x += 1) {
      if (!grid.isPassable(x, y) || seen.has(`${x},${y}`)) continue;
      components += 1;
      const stack = [[x, y]];
      seen.add(`${x},${y}`);
      while (stack.length > 0) {
        const [cx, cy] = stack.pop();
        for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
          const key = `${cx + dx},${cy + dy}`;
          if (seen.has(key) || !grid.isPassable(cx + dx, cy + dy)) continue;
          seen.add(key);
          stack.push([cx + dx, cy + dy]);
        }
      }
    }
  }
  return components;
}
